version: '3'

services:
  kong:
    build:
      context: kong
      dockerfile: ./Dockerfile
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_PLUGINS: bundled,oauth2-token-introspection-request
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
    - 8000:8000